### ISSUE TITLE
This also applies on non-hexagonal maps, which breaks tile usage there

### ISSUE THREAD

**Issue by icopp** [hitcherland/FoundryVTT-Better-Hexagonal-Tiles#4]
This breaks use of tiles for anything that uses mixed maps (for example, hex exploration maps with square combat grids).

**Comment by hitcherland** [comment]
Sorry for the delay! should be fixed now with v1.2

**Comment by WBHarry** [comment]
I do believe this was fixed in v1.2, but the download link in the new version is still pointing to 1.1, so it can't be downloaded via Foundry.
![image](https://user-images.githubusercontent.com/89362246/219618506-7df56031-1be8-4829-af96-2974de12d45f.png)
Awesome mod though 😁 
Edit: Or maybe it's a problem with minimum/verified. I'm unsure. It won't update past 1.1 on Foundry v10 at the very least!

**Comment by hitcherland** [comment]
Agh, no that's the problem. I _think_ I've fixed it in 1.3
